project_id = "qmnhbtmnarhnvbmpskuu"

[functions.download-product]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.verify-order]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false
